# Generated by Django 6.0.6 on 2026-07-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bugs", "0004_alter_qaresult_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="bughistory",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
